services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  pubsub:
    build:
      context: ./pubsub
    container_name: pubsub
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9093
    extra_hosts:
      - "my-localhost:host-gateway"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000

  generator_agent:
    build:
      context: .
      dockerfile: generator_agent.Dockerfile
    container_name: generator_agent
    ports:
      - "8001:8080"
    depends_on:
      - pubsub
    env_file:
      - ./generator_agent/app/.env
    environment:
      PUBSUB_URL: http://pubsub:8000
      RECEIVE_URL: http://generator_agent:8080
    extra_hosts:
      - "my-localhost:host-gateway"
  builder_agent:
      build:
        context: .
        dockerfile: builder_agent.Dockerfile
      container_name: builder_agent
      ports:
        - "8002:8080"
      depends_on:
        - pubsub
      env_file:
        - ./builder_agent/.env
      environment:
        PUBSUB_URL: http://pubsub:8000
        RECEIVE_URL: http://builder_agent:8080
      extra_hosts:
        - "my-localhost:host-gateway"
  chat_agent:
    build:
      context: .
      dockerfile: chat_agent.Dockerfile
    container_name: chat_agent
    ports:
      - "8003:8003"
    depends_on:
      - pubsub
    env_file:
      - ./chat_agent/app/.env
    environment:
      PUBSUB_URL: http://pubsub:8000
      AGENT_HOST: chat_agent
      AGENT_PORT: 8003
    extra_hosts:
      - "my-localhost:host-gateway"
  github-mcp-server:
    image: ghcr.io/github/github-mcp-server
    ports:
      - "8004:8004"
    env_file:
      - ./.env
    stdin_open: true  # -i
    tty: true         # makes it interactive if needed
    restart: "no"     # --rm is similar to no restart
  breba-app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: breba-app
    ports:
      - "8080:8080"
    depends_on:
      - pubsub
    environment:
      PUBSUB_URL: http://pubsub:8000
      HOST: breba-app
      PORT: 8080
    extra_hosts:
      - "my-localhost:host-gateway"