services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  pubsub:
    build:
      context: ./pubsub
    container_name: pubsub
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9093
    extra_hosts:
      - "my-localhost:host-gateway"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000

  output_agent:
    build:
      context: .
      dockerfile: output_agent.Dockerfile
    container_name: output_agent
    ports:
      - "8001:8001"
    depends_on:
      - pubsub
    env_file:
      - ./output_agent/app/.env
    environment:
      PUBSUB_URL: http://pubsub:8000
      AGENT_HOST: output_agent
      AGENT_PORT: 8001
    extra_hosts:
      - "my-localhost:host-gateway"
#    command: >
#      uvicorn main:app --host 0.0.0.0 --port 8001
