services:
  breba-app:
    build:
      context: .
      dockerfile: breba_app.Dockerfile
    container_name: breba-app
    ports:
      - "8080:8080"
    env_file:
      - ./breba_app/.env
    environment:
      HOST: breba-app
      PORT: 8080