# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def CoderNotes(self, messages: typing.List["types.LLMMessage"],coder_notes: str,index_html: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CoderNotes(messages=messages,coder_notes=coder_notes,index_html=index_html,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CoderNotes", args={
                "messages": messages,"coder_notes": coder_notes,"index_html": index_html,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DescribeMedia(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ImageClassification", "types.QuestionToUser"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DescribeMedia(messages=messages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DescribeMedia", args={
                "messages": messages,
            })
            return typing.cast(typing.Union["types.ImageClassification", "types.QuestionToUser"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DetermineFilesToEdit(self, messages: typing.List["types.LLMMessage"],files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.FileList:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DetermineFilesToEdit(messages=messages,files=files,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DetermineFilesToEdit", args={
                "messages": messages,"files": files,
            })
            return typing.cast(types.FileList, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateSearchReplaceBlocks(self, messages: typing.List["types.LLMMessage"],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateSearchReplaceBlocks(messages=messages,agents_md=agents_md,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateSearchReplaceBlocks", args={
                "messages": messages,"agents_md": agents_md,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def PickActionForUpload(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.UplaodAsset", "types.Inference", "types.QuestionToUser"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.PickActionForUpload(messages=messages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="PickActionForUpload", args={
                "messages": messages,
            })
            return typing.cast(typing.Union["types.UplaodAsset", "types.Inference", "types.QuestionToUser"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ShouldUploadToAssets(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> types.UploadToAssets:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ShouldUploadToAssets(messages=messages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ShouldUploadToAssets", args={
                "messages": messages,
            })
            return typing.cast(types.UploadToAssets, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def UserResponseOrCoder(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ResponseToUser", "types.Coder"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.UserResponseOrCoder(messages=messages,spec=spec,files=files,agents_md=agents_md,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="UserResponseOrCoder", args={
                "messages": messages,"spec": spec,"files": files,"agents_md": agents_md,
            })
            return typing.cast(typing.Union["types.ResponseToUser", "types.Coder"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def UserResponseOrCoder2(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ResponseToUser", "types.Coder"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.UserResponseOrCoder2(messages=messages,spec=spec,files=files,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="UserResponseOrCoder2", args={
                "messages": messages,"spec": spec,"files": files,
            })
            return typing.cast(typing.Union["types.ResponseToUser", "types.Coder"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CoderNotes(self, messages: typing.List["types.LLMMessage"],coder_notes: str,index_html: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CoderNotes", args={
            "messages": messages,"coder_notes": coder_notes,"index_html": index_html,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DescribeMedia(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.ImageClassification", "stream_types.QuestionToUser"], typing.Union["types.ImageClassification", "types.QuestionToUser"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DescribeMedia", args={
            "messages": messages,
        })
        return baml_py.BamlStream[typing.Union["stream_types.ImageClassification", "stream_types.QuestionToUser"], typing.Union["types.ImageClassification", "types.QuestionToUser"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.ImageClassification", "stream_types.QuestionToUser"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.ImageClassification", "types.QuestionToUser"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DetermineFilesToEdit(self, messages: typing.List["types.LLMMessage"],files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.FileList, types.FileList]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DetermineFilesToEdit", args={
            "messages": messages,"files": files,
        })
        return baml_py.BamlStream[stream_types.FileList, types.FileList](
          __result__,
          lambda x: typing.cast(stream_types.FileList, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FileList, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateSearchReplaceBlocks(self, messages: typing.List["types.LLMMessage"],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateSearchReplaceBlocks", args={
            "messages": messages,"agents_md": agents_md,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PickActionForUpload(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.UplaodAsset", "stream_types.Inference", "stream_types.QuestionToUser"], typing.Union["types.UplaodAsset", "types.Inference", "types.QuestionToUser"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="PickActionForUpload", args={
            "messages": messages,
        })
        return baml_py.BamlStream[typing.Union["stream_types.UplaodAsset", "stream_types.Inference", "stream_types.QuestionToUser"], typing.Union["types.UplaodAsset", "types.Inference", "types.QuestionToUser"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.UplaodAsset", "stream_types.Inference", "stream_types.QuestionToUser"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.UplaodAsset", "types.Inference", "types.QuestionToUser"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ShouldUploadToAssets(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.UploadToAssets, types.UploadToAssets]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ShouldUploadToAssets", args={
            "messages": messages,
        })
        return baml_py.BamlStream[stream_types.UploadToAssets, types.UploadToAssets](
          __result__,
          lambda x: typing.cast(stream_types.UploadToAssets, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.UploadToAssets, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def UserResponseOrCoder(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], typing.Union["types.ResponseToUser", "types.Coder"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="UserResponseOrCoder", args={
            "messages": messages,"spec": spec,"files": files,"agents_md": agents_md,
        })
        return baml_py.BamlStream[typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], typing.Union["types.ResponseToUser", "types.Coder"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.ResponseToUser", "types.Coder"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def UserResponseOrCoder2(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], typing.Union["types.ResponseToUser", "types.Coder"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="UserResponseOrCoder2", args={
            "messages": messages,"spec": spec,"files": files,
        })
        return baml_py.BamlStream[typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], typing.Union["types.ResponseToUser", "types.Coder"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.ResponseToUser", "types.Coder"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def CoderNotes(self, messages: typing.List["types.LLMMessage"],coder_notes: str,index_html: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CoderNotes", args={
            "messages": messages,"coder_notes": coder_notes,"index_html": index_html,
        }, mode="request")
        return __result__
    async def DescribeMedia(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeMedia", args={
            "messages": messages,
        }, mode="request")
        return __result__
    async def DetermineFilesToEdit(self, messages: typing.List["types.LLMMessage"],files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetermineFilesToEdit", args={
            "messages": messages,"files": files,
        }, mode="request")
        return __result__
    async def GenerateSearchReplaceBlocks(self, messages: typing.List["types.LLMMessage"],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateSearchReplaceBlocks", args={
            "messages": messages,"agents_md": agents_md,
        }, mode="request")
        return __result__
    async def PickActionForUpload(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PickActionForUpload", args={
            "messages": messages,
        }, mode="request")
        return __result__
    async def ShouldUploadToAssets(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ShouldUploadToAssets", args={
            "messages": messages,
        }, mode="request")
        return __result__
    async def UserResponseOrCoder(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="UserResponseOrCoder", args={
            "messages": messages,"spec": spec,"files": files,"agents_md": agents_md,
        }, mode="request")
        return __result__
    async def UserResponseOrCoder2(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="UserResponseOrCoder2", args={
            "messages": messages,"spec": spec,"files": files,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def CoderNotes(self, messages: typing.List["types.LLMMessage"],coder_notes: str,index_html: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CoderNotes", args={
            "messages": messages,"coder_notes": coder_notes,"index_html": index_html,
        }, mode="stream")
        return __result__
    async def DescribeMedia(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DescribeMedia", args={
            "messages": messages,
        }, mode="stream")
        return __result__
    async def DetermineFilesToEdit(self, messages: typing.List["types.LLMMessage"],files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetermineFilesToEdit", args={
            "messages": messages,"files": files,
        }, mode="stream")
        return __result__
    async def GenerateSearchReplaceBlocks(self, messages: typing.List["types.LLMMessage"],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateSearchReplaceBlocks", args={
            "messages": messages,"agents_md": agents_md,
        }, mode="stream")
        return __result__
    async def PickActionForUpload(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PickActionForUpload", args={
            "messages": messages,
        }, mode="stream")
        return __result__
    async def ShouldUploadToAssets(self, messages: typing.List["types.LLMMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ShouldUploadToAssets", args={
            "messages": messages,
        }, mode="stream")
        return __result__
    async def UserResponseOrCoder(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],agents_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="UserResponseOrCoder", args={
            "messages": messages,"spec": spec,"files": files,"agents_md": agents_md,
        }, mode="stream")
        return __result__
    async def UserResponseOrCoder2(self, messages: typing.List["types.LLMMessage"],spec: str,files: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="UserResponseOrCoder2", args={
            "messages": messages,"spec": spec,"files": files,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))