# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (8)
# #########################################################################

class Coder(BaseModel):
    invoke_coder: bool

class FileList(BaseModel):
    reasoning: str = Field(description='Explanation of why these files need to be edited or not in one short sentence.')
    files: typing.List[str] = Field(description='List of file paths to edit.')

class ImageClassification(BaseModel):
    intent: str = Field(description='User intent for the upload')
    reason: str = Field(description='Reason why you chose this intent')

class Inference(BaseModel):
    inference_only: bool = Field(description='Always true')

class LLMMessage(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    content: str
    images: typing.Optional[typing.List[baml_py.Image]] = None

class QuestionToUser(BaseModel):
    response_to_user: str = Field(description='Clarification of the issue with the request')

class ResponseToUser(BaseModel):
    response_to_user: str

class UplaodAsset(BaseModel):
    upload_asset: bool = Field(description='User needs to upload assest to be used as part of website contents.')
    inference: bool = Field(description='Always true')
    reason: str = Field(description='Reason why you chose to upload the assets')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
